{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Employee",
        "Service": "/projectPacer/Services/pacerMdk.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "FullName": "#Control:FullName/#Value",
        "Role": "#Control:Role/#Value",
        "isActive": "#Control:isActive/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/projectPacer/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/projectPacer/Actions/UpdateEntityFailureMessage.action"
}