{
    "Service": "/projectPacer/Services/pacerMdk.service",
    "DefiningRequests": [{
            "Name": "Employee",
            "Query": "Employee"
        },
        {
            "Name": "LinkEntity",
            "Query": "LinkEntity"
        },
        {
            "Name": "WBS",
            "Query": "WBS"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnSuccess": "/projectPacer/Actions/Service/InitializeOfflineSuccessMessage.action",
    "OnFailure": "/projectPacer/Actions/Service/InitializeOfflineFailureMessage.action"
}